apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hkh-autopilot
resources:
- ../../base
- postgres-backup.yaml
images:
- name: admin-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-admin
  newTag: sha-6b778f8
- name: backend-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-backend
  newTag: sha-d597fbd
- name: frontend-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-frontend
  newTag: sha-e85bc96
