apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hkh-autopilot
resources:
- ../../base
- postgres-backup.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/hkh.vdzonsoftware.nl~1runtime-secret-checksum
      value: "8feb08fc4a2eae0c26a16b62320fdaed96e7c16b8fad0338e50e79d846d98f1d"
  target:
    group: apps
    kind: Deployment
    name: backend
    version: v1
images:
- name: admin-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-admin
  newTag: sha-fac1946
- name: backend-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-backend
  newTag: sha-08e5f3a
- name: frontend-image
  newName: ghcr.io/robbertvdzon/hkh-autopilot-frontend
  newTag: sha-08e5f3a
