apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hkh-autopilot
resources:
  - ../../base
images:
  - name: backend-image
    newName: ghcr.io/robbertvdzon/hkh-autopilot-backend
    newTag: main
  - name: frontend-image
    newName: ghcr.io/robbertvdzon/hkh-autopilot-frontend
    newTag: main
  - name: admin-image
    newName: ghcr.io/robbertvdzon/hkh-autopilot-admin
    newTag: main
