apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-rbac.yaml
  - database-service.yaml
  - database-statefulset.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-route.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-route.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - admin-route.yaml
  - sealed-secret-runtime.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hkh
