apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hkh-autopilot-acceptance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/robbertvdzon/hkh-autopilot.git
    targetRevision: main
    path: deploy/overlays/acceptance
  destination:
    server: https://kubernetes.default.svc
    namespace: hkh-autopilot-acceptance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 5
