apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    metadata:
      annotations:
        ai-access.vdzonsoftware.nl/config-version: '2026-09-15'
    spec:
      containers:
      - name: backend
        env:
        - name: AI_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: ai-access
              key: AI_ACCESS_TOKEN
        - name: AI_ACCESS_EMAILS
          valueFrom:
            secretKeyRef:
              name: ai-access
              key: AI_ACCESS_EMAILS
        - name: AI_ACCESS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: ai-access
              key: AI_ACCESS_ALLOWED_ORIGINS
        - name: HKH_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ai-access
              key: HKH_GOOGLE_CLIENT_ID
        - name: HKH_ADMIN_ALLOWED_EMAILS
          valueFrom:
            secretKeyRef:
              name: ai-access
              key: HKH_ADMIN_ALLOWED_EMAILS
        - name: HKH_CORS_ALLOWED_ORIGIN_PATTERNS
          valueFrom: null
          value: https://hkh-autopilot-acceptance.vdzonsoftware.nl,https://hkh-autopilot-admin-acceptance.vdzonsoftware.nl
